
# set server port
server:
    port: ${PORT:9080}
    contextPath: /api/${application.finalName}

# Spring Cloud - Config Server
## give name for discovery
spring:
    application:
        name: configuration-service
## URI to config-server
# spring:
#	cloud:
#		config:
#			uri: http://localhost:8080/
## Database
    data:
        mongodb:
            uri: mongodb://localhost/
            database: marketplace-dev

application:
    finalName: configuration-service-dev
## base path to migration script
    property:
        mongobee:
            changelog:
                path: inspectit.rocks.marketplace.configuration.service.migration.mongobee
                enabled: true

# disable security for actuator
## only for dev
management:
    security:
        enabled: false

# setup eureka if context-path is used
eureka:
    instance:
        metadataMap:
            management:
                context-path: ${server.contextPath}
        statusPageUrlPath: ${server.contextPath}/info
        healthCheckUrlPath: ${server.contextPath}/health